enum TileId {
	Boundary,
	Empty,
	Soil,
	Soil_,
	Soil__,
	Soil___,
	Iron,
	Iron_,
	Iron__,
	Iron___,
	Silver,
	Silver_,
	Silver__,
	Silver___,
	Gold,
	Gold_,
	Gold__,
	Gold___,
	Sapphire,
	Sapphire_,
	Sapphire__,
	Sapphire___,
	Emerald,
	Emerald_,
	Emerald__,
	Emerald___,
	Ruby,
	Ruby_,
	Ruby__,
	Ruby___,
	Diamond,
	Diamond_,
	Diamond__,
	Diamond___,
	Rock,
	Rock_,
	Rock__,
	Rock___,
	Rock____,
	IronInRock,
	IronInRock_,
	IronInRock__,
	IronInRock___,
	IronInRock____,
	SilverInRock,
	SilverInRock_,
	SilverInRock__,
	SilverInRock___,
	SilverInRock____,
	GoldInRock,
	GoldInRock_,
	GoldInRock__,
	GoldInRock___,
	GoldInRock____,
	SapphireInRock,
	SapphireInRock_,
	SapphireInRock__,
	SapphireInRock___,
	SapphireInRock____,
	EmeraldInRock,
	EmeraldInRock_,
	EmeraldInRock__,
	EmeraldInRock___,
	EmeraldInRock____,
	RubyInRock,
	RubyInRock_,
	RubyInRock__,
	RubyInRock___,
	RubyInRock____,
	DiamondInRock,
	DiamondInRock_,
	DiamondInRock__,
	DiamondInRock___,
	DiamondInRock____,
}


const TILE_DATA = {
TileId.Empty: {g = Vector2i(-1, -1), o = Vector2i(-1, -1), to = TileId.Empty, s = 0.15},
TileId.Boundary: {g = Vector2i(0, 0), o = Vector2i(-1, -1), to = TileId.Boundary, s = 0.15},
TileId.Soil: {g = Vector2i(0, 1), o = Vector2i(-1, -1), to = TileId.Soil_, s = 0.15},
TileId.Soil_: {g = Vector2i(1, 1), o = Vector2i(-1, -1), to = TileId.Soil__, s = 0.15},
TileId.Soil__: {g = Vector2i(2, 1), o = Vector2i(-1, -1), to = TileId.Empty, s = 0.15},
TileId.Soil___: {g = Vector2i(3, 1), o = Vector2i(-1, -1), to = TileId.Empty, s = 0.15},
TileId.Rock: {g = Vector2i(0, 2), o = Vector2i(-1, -1), to = TileId.Rock_, s = 0.4},
TileId.Rock_: {g = Vector2i(1, 2), o = Vector2i(-1, -1), to = TileId.Rock__, s = 0.5},
TileId.Rock__: {g = Vector2i(2, 2), o = Vector2i(-1, -1), to = TileId.Rock___, s = 0.4},
TileId.Rock___: {g = Vector2i(3, 2), o = Vector2i(-1, -1), to = TileId.Empty, s = 0.2},
TileId.Rock____: {g = Vector2i(4, 2), o = Vector2i(-1, -1), to = TileId.Empty, s = 0.2},
TileId.Iron: {g = Vector2i(0, 1), o = Vector2i(0, 3), to = TileId.Iron_, s = 0.15},
TileId.Iron_: {g = Vector2i(1, 1), o = Vector2i(0, 3), to = TileId.Iron__, s = 0.15},
TileId.Iron__: {g = Vector2i(2, 1), o = Vector2i(0, 3), to = TileId.Empty, s = 0.15, p = 10},
TileId.Iron___: {g = Vector2i(3, 1), o = Vector2i(0, 3), to = TileId.Empty, s = 0.15, p = 10},
TileId.Silver: {g = Vector2i(0, 1), o = Vector2i(0, 4), to = TileId.Silver_, s = 0.15},
TileId.Silver_: {g = Vector2i(1, 1), o = Vector2i(0, 4), to = TileId.Silver__, s = 0.15},
TileId.Silver__: {g = Vector2i(2, 1), o = Vector2i(0, 4), to = TileId.Empty, s = 0.15, p = 25},
TileId.Silver___: {g = Vector2i(3, 1), o = Vector2i(0, 4), to = TileId.Empty, s = 0.15, p = 25},
TileId.Gold: {g = Vector2i(0, 1), o = Vector2i(0, 5), to = TileId.Gold_, s = 0.15},
TileId.Gold_: {g = Vector2i(1, 1), o = Vector2i(0, 5), to = TileId.Gold__, s = 0.15},
TileId.Gold__: {g = Vector2i(2, 1), o = Vector2i(0, 5), to = TileId.Empty, s = 0.15, p = 50},
TileId.Gold___: {g = Vector2i(3, 1), o = Vector2i(0, 5), to = TileId.Empty, s = 0.15, p = 50},
TileId.Sapphire: {g = Vector2i(0, 1), o = Vector2i(0, 6), to = TileId.Sapphire_, s = 0.15},
TileId.Sapphire_: {g = Vector2i(1, 1), o = Vector2i(0, 6), to = TileId.Sapphire__, s = 0.15},
TileId.Sapphire__: {g = Vector2i(2, 1), o = Vector2i(0, 6), to = TileId.Empty, s = 0.15, p = 75},
TileId.Sapphire___: {g = Vector2i(3, 1), o = Vector2i(0, 6), to = TileId.Empty, s = 0.15, p = 75},
TileId.Emerald: {g = Vector2i(0, 1), o = Vector2i(0, 7), to = TileId.Emerald_, s = 0.15},
TileId.Emerald_: {g = Vector2i(1, 1), o = Vector2i(0, 7), to = TileId.Emerald__, s = 0.15},
TileId.Emerald__: {g = Vector2i(2, 1), o = Vector2i(0, 7), to = TileId.Empty, s = 0.15, p = 100},
TileId.Emerald___: {g = Vector2i(3, 1), o = Vector2i(0, 7), to = TileId.Empty, s = 0.15, p = 100},
TileId.Ruby: {g = Vector2i(0, 1), o = Vector2i(0, 8), to = TileId.Ruby_, s = 0.15},
TileId.Ruby_: {g = Vector2i(1, 1), o = Vector2i(0, 8), to = TileId.Ruby__, s = 0.15},
TileId.Ruby__: {g = Vector2i(2, 1), o = Vector2i(0, 8), to = TileId.Empty, s = 0.15, p = 150},
TileId.Ruby___: {g = Vector2i(3, 1), o = Vector2i(0, 8), to = TileId.Empty, s = 0.15, p = 150},
TileId.Diamond: {g = Vector2i(0, 1), o = Vector2i(0, 9), to = TileId.Diamond_, s = 0.15},
TileId.Diamond_: {g = Vector2i(1, 1), o = Vector2i(0, 9), to = TileId.Diamond__, s = 0.15},
TileId.Diamond__: {g = Vector2i(2, 1), o = Vector2i(0, 9), to = TileId.Empty, s = 0.15, p = 250},
TileId.Diamond___: {g = Vector2i(3, 1), o = Vector2i(0, 9), to = TileId.Empty, s = 0.15, p = 250},
# 
TileId.IronInRock: {g = Vector2i(0, 2), o = Vector2i(0, 11 - 8), to = TileId.IronInRock_, s = 0.4},
TileId.IronInRock_: {g = Vector2i(1, 2), o = Vector2i(0, 11 - 8), to = TileId.IronInRock__, s = 0.5},
TileId.IronInRock__: {g = Vector2i(2, 2), o = Vector2i(0, 11 - 8), to = TileId.IronInRock___, s = 0.4},
TileId.IronInRock___: {g = Vector2i(3, 2), o = Vector2i(0, 11 - 8), to = TileId.Empty, s = 0.2, p = 10},
TileId.IronInRock____: {g = Vector2i(4, 2), o = Vector2i(0, 11 - 8), to = TileId.Empty, s = 0.2, p = 10},
TileId.SilverInRock: {g = Vector2i(0, 2), o = Vector2i(0, 12 - 8), to = TileId.SilverInRock_, s = 0.4},
TileId.SilverInRock_: {g = Vector2i(1, 2), o = Vector2i(0, 12 - 8), to = TileId.SilverInRock__, s = 0.5},
TileId.SilverInRock__: {g = Vector2i(2, 2), o = Vector2i(0, 12 - 8), to = TileId.SilverInRock___, s = 0.4},
TileId.SilverInRock___: {g = Vector2i(3, 2), o = Vector2i(0, 12 - 8), to = TileId.Empty, s = 0.2, p = 25},
TileId.SilverInRock____: {g = Vector2i(4, 2), o = Vector2i(0, 12 - 8), to = TileId.Empty, s = 0.2, p = 25},
TileId.GoldInRock: {g = Vector2i(0, 2), o = Vector2i(0, 13 - 8), to = TileId.GoldInRock_, s = 0.4},
TileId.GoldInRock_: {g = Vector2i(1, 2), o = Vector2i(0, 13 - 8), to = TileId.GoldInRock__, s = 0.5},
TileId.GoldInRock__: {g = Vector2i(2, 2), o = Vector2i(0, 13 - 8), to = TileId.GoldInRock___, s = 0.4},
TileId.GoldInRock___: {g = Vector2i(3, 2), o = Vector2i(0, 13 - 8), to = TileId.Empty, s = 0.2, p = 50},
TileId.GoldInRock____: {g = Vector2i(4, 2), o = Vector2i(0, 13 - 8), to = TileId.Empty, s = 0.2, p = 50},
TileId.SapphireInRock: {g = Vector2i(0, 2), o = Vector2i(0, 14 - 8), to = TileId.SapphireInRock_, s = 0.4},
TileId.SapphireInRock_: {g = Vector2i(1, 2), o = Vector2i(0, 14 - 8), to = TileId.SapphireInRock__, s = 0.5},
TileId.SapphireInRock__: {g = Vector2i(2, 2), o = Vector2i(0, 14 - 8), to = TileId.SapphireInRock___, s = 0.4},
TileId.SapphireInRock___: {g = Vector2i(3, 2), o = Vector2i(0, 14 - 8), to = TileId.Empty, s = 0.2, p = 75},
TileId.SapphireInRock____: {g = Vector2i(4, 2), o = Vector2i(0, 14 - 8), to = TileId.Empty, s = 0.2, p = 75},
TileId.EmeraldInRock: {g = Vector2i(0, 2), o = Vector2i(0, 15 - 8), to = TileId.EmeraldInRock_, s = 0.4},
TileId.EmeraldInRock_: {g = Vector2i(1, 2), o = Vector2i(0, 15 - 8), to = TileId.EmeraldInRock__, s = 0.5},
TileId.EmeraldInRock__: {g = Vector2i(2, 2), o = Vector2i(0, 15 - 8), to = TileId.EmeraldInRock___, s = 0.4},
TileId.EmeraldInRock___: {g = Vector2i(3, 2), o = Vector2i(0, 15 - 8), to = TileId.Empty, s = 0.2, p = 100},
TileId.EmeraldInRock____: {g = Vector2i(4, 2), o = Vector2i(0, 15 - 8), to = TileId.Empty, s = 0.2, p = 100},
TileId.RubyInRock: {g = Vector2i(0, 2), o = Vector2i(0, 16 - 8), to = TileId.RubyInRock_, s = 0.4},
TileId.RubyInRock_: {g = Vector2i(1, 2), o = Vector2i(0, 16 - 8), to = TileId.RubyInRock__, s = 0.5},
TileId.RubyInRock__: {g = Vector2i(2, 2), o = Vector2i(0, 16 - 8), to = TileId.RubyInRock___, s = 0.4},
TileId.RubyInRock___: {g = Vector2i(3, 2), o = Vector2i(0, 16 - 8), to = TileId.Empty, s = 0.2, p = 150},
TileId.RubyInRock____: {g = Vector2i(4, 2), o = Vector2i(0, 16 - 8), to = TileId.Empty, s = 0.2, p = 150},
TileId.DiamondInRock: {g = Vector2i(0, 2), o = Vector2i(0, 17 - 8), to = TileId.DiamondInRock_, s = 0.4},
TileId.DiamondInRock_: {g = Vector2i(1, 2), o = Vector2i(0, 17 - 8), to = TileId.DiamondInRock__, s = 0.5},
TileId.DiamondInRock__: {g = Vector2i(2, 2), o = Vector2i(0, 17 - 8), to = TileId.DiamondInRock___, s = 0.4},
TileId.DiamondInRock___: {g = Vector2i(3, 2), o = Vector2i(0, 17 - 8), to = TileId.Empty, s = 0.2, p = 250},
TileId.DiamondInRock____: {g = Vector2i(4, 2), o = Vector2i(0, 17 - 8), to = TileId.Empty, s = 0.2, p = 250},
}
